language: java

jdk:
  - oraclejdk8

# blacklist
branches:
  except:
    - javafx-gui

# whitelist
branches:
  only:
    - master
    - network

before_install:
  - pip install --user codecov
after_success:
  - codecov